### ISSUE TITLE
where is mac-agora plugin source code?

### ISSUE THREAD

**Issue by SupranJowti** [AgoraIO/OBS#25]
where is mac-agora plugin source code?

**Comment by SupranJowti** [comment]
I want to build an agora plugin in obs. is it possible in mac?

**Comment by plutoless** [comment]
it's the same code base, we actually do have a readme in chinese but not yet in english..
i'll ask my colleague to add one.
https://github.com/AgoraIO/OBS/blob/agora-tool-ui-3.3.0/README.zh.md
maybe you can use google translate for now

**Comment by sbd021** [comment]
Reference to https://github.com/AgoraIO/OBS/blob/agora-tool-ui-3.3.0/README.md. Now "Compling Agora RTC Tool" includes Windows and Mac.  You need to build obs studio first.

**Comment by SupranJowti** [comment]
![Screen Shot 2021-04-26 at 15 56 29](https://user-images.githubusercontent.com/7446304/116043739-fe896380-a6aa-11eb-81c3-f3f8faf0fa1a.png)

Generated successfully, but "Agora Rtc Tool" does not show in the Tool menu. I am started obs from obs-studio/build/rundir/RelWithDebInfo/bin

Am I in the correct way?

**Comment by sbd021** [comment]
1. copy Agoraxxxx.framework to Frameworks folder under Obs
2. copy libagora-tool-ui.so to Plugins folder under obs.
3. copy libagora-tool-ui under data to resources/data/obs-plugins folder.
4. then run obs, select tool in obs menu bar. There's a sub-menu item about agora.
