### ISSUE TITLE
Failed to build branch agora-tool-ui-3.6.200

### ISSUE THREAD

**Issue by icewindq** [AgoraIO/OBS#32]
Hey guys,
I have set up the building environment according to the manual page. I built the branch `agora-tool-ui-3.3.3` successfully. but it failed when I build the branch `agora-tool-ui-3.6.200`. There are some errors like `namespace "agora::rtc" has no member "RtcConnection"` Please refer to the below screenshot. 
![image](https://user-images.githubusercontent.com/6817601/146920548-f6487e74-f114-4f7c-abe1-3759cb23970e.png)
It seems the Agora SDK isn't the latest. But I think I already use the latest one `Windows v3.6.0`.

Build Environment

- Windows 10 x64
- Vistual Studio 2019
- Agora SDK Windows v3.6.0

**Comment by sbd021** [comment]
Download latest deps: https://github.com/AgoraIO/OBS/releases/download/3.6.200/deps.zip

**Comment by sbd021** [comment]
Download latest deps that includes agora sdk 3.6.200: https://github.com/AgoraIO/OBS/releases/download/3.6.200/deps.zip.

**Comment by icewindq** [comment]
thanks a lot. It build successfully with the latest deps. I overwrite the deps with the latest agora windows sdk, that caused this issue.
